### ISSUE TITLE
Issue with Zuul integration

### ISSUE THREAD

**Issue by Keitaro75** [jmnarloch/ribbon-discovery-filter-spring-cloud-starter#1]
Hello,

I tried to use your project with Zuul.
However, I have a problem.
This is my scenario :
- Get to service A : /test1/
- Get to service B : /test2/
- Get to service A : /test1/ => Bad request, zuul redirects my request to service B.

Indeed, the LoadBalancer set into the rules doesn't contains any reference to my service A after the call to the service B. It's erased by com.netflix.loadbalancer.BaseLoadBalancer:360
`this.rule.setLoadBalancer(this);`

In the usually case, the rule is instanciated for each service, but in my case, it's defined by RibbonDiscoveryRuleAutoConfiguration class.
`this.rule = new RoundRobinRule()`

Do you have an idea to fix this problem ?

Thanks.

**Comment by jmnarloch** [comment]
I can take a loot into this matter, would you mind sharing minimal configuration? Are you using service discovery for the routes, or just fixed urls?

**Comment by Keitaro75** [comment]
Hello,

I fix the issue by using the MetadataAwareRule in prototype scope.

```
        @Bean
    @Scope("prototype")
    public DiscoveryEnabledRule metadataAwareRule() {
        return new MetadataAwareRule();
    }
```

I use the discovery for routes (Zuul + Eureka).

Thanks.

**Comment by jmnarloch** [comment]
@Keitaro75 Thanks for your feedback, I will prepare proper pull request.

Since the RibbonDiscoveryRuleAutoConfiguration had proper conditional you can use your own bean definition in your application till the next release, but this should happen soon.
