### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by pradeepkusingh** [jmnarloch/ribbon-discovery-filter-spring-cloud-starter#2]
How to achieve session stickyness using ribbon with Zuul ? is this api support it ?

**Comment by jmnarloch** [comment]
I would suggest asking this question either within Netflix Zuul or Ribbon projects. Second of all you probably don't want to have session in microservice world. Stateful services does not scale well. If you need that only for authentication, then OAuth is a kind of solution.

**Comment by jmnarloch** [comment]
Closing issue
